#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SPRING
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring:
  application:
    name: monetary-api
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL92Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/monetary?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# INFRA
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

server:
  port: 8094

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# LOGGING
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
logging:
  level:
    com.maxijett.monetary: DEBUG

kafka:
  topics:
    orderPayment:
      name: orderPayment

dailyBonus:
  hot:
    rate: 0.09
  cold:
    rate: 0.032
    opening: 5
    divide: 100
  nightShift:
    rate: 1.5
    minValue: 15
    size: 10

shiftTime:
  nightShift:
    startHour: 23
    endHour: 3
    minute: 30
  morningShift:
    startHour: 9
    endHour: 11
