package com.maxijett.monetary.store.model.enumeration;

public enum StoreEventType {
    PACKAGE_DELIVERED, SUPPORT_ACCEPTED, DRIVER_PAY, ADMIN_GET_PAID, STORE_PAYMENT_BACK, ADMIN_PAYMENT_BACK, REFUND_OF_PAYMENT, COLD_STORE_COLLECTION

}
